### ISSUE TITLE
Add Live Directory Watching.

### ISSUE THREAD

**Issue by RayhanADev** [CoolCoderSJ/replit-cli#11]
If you have most commands (i.e. write, move, create, delete) then integrate with a file watching module in Python and you have easy directory watching! Just run the command when a certain event happens. I use chokidar for my NodeJS cli so there may be a Python equivalent. If you need any technical help with how that looks I can help in our Discord group.

**Comment by CoolCoderSJ** [comment]
Thanks yeah, I'll take a look into file watching services and push the file on change.
Have you added watching on the server to automatically pull yet? If so, how'd ya do that? My idea would be to get the contents of each file every x seconds but that seems like a bad idea.

**Comment by CoolCoderSJ** [comment]
By server I meant the replit server. My client connects directly to goval too (except for push because I'm still working out a few things)

**Comment by CoolCoderSJ** [comment]
Right yeah so pushing changes should be easy, still wondering how to fetch changes...

**Comment by RayhanADev** [comment]
> Right yeah so pushing changes should be easy, still wondering how to fetch changes...

That's when you have to get into *operational transformations* which is a beast unto itself. I'm working out my own model (and maybe starred a few useful repos) but you should ask miro since they seem to know more about them atm.

**Comment by CoolCoderSJ** [comment]
Its a bit conky but works :D

**Comment by RayhanADev** [comment]
@CoolCoderSJ awesome!
