### ISSUE TITLE
Error - Selenium not added as a dependency

### ISSUE THREAD

**Issue by Kudostoy0u** [CoolCoderSJ/replit-cli#4]
![image](https://user-images.githubusercontent.com/69732000/121969877-d75e2280-cd3a-11eb-95c4-a02d29de5912.png)

Installed on (Garuda) Linux using pip.

**Comment by CoolCoderSJ** [comment]
Sorry about that- I've fixed it and republished it under version 1.0.6.
```
pip install repl-cli==1.0.6
```
