### ISSUE TITLE
Error from Protobuf - "TypeError: Descriptors should not be created directly, but only retrieved from their parent."

### ISSUE THREAD

**Issue by Kudostoy0u** [CoolCoderSJ/replit-cli#5]
On manual installation of Selenium, the following error occured.
![image](https://user-images.githubusercontent.com/69732000/121970136-7c78fb00-cd3b-11eb-9ab1-b096fda9c296.png)

Installed on (Garuda) Linux using pip.

**Comment by CoolCoderSJ** [comment]
This seems to be a Unix issue, I'm looking into it. Will notify for updates.

**Comment by CoolCoderSJ** [comment]
@Kudostoy0u sorry for that- Ive fixed it now. Update Replit CLI to 1.0.9
```
pip install --upgrade repl-cli==1.0.9
```
If the issue persists, try uninstalling and installing the library ` protobuf ` and make sure it is at version ` 3.17.x `
It seems to be working on my Ubuntu machine now, so I'll be closing this.

**Comment by CoolCoderSJ** [comment]
Actually, I'll reopen until you confirm that it works for you. I had to reinstall it multiple times (its very finicky)
If it doesn't work, then do
```
pip install python3-protobuf
pip uninstall python3-protobuf
pip uninstall protobuf
pip install --upgrade protobuf
```
