### ISSUE TITLE
Can't `replit login` with a Google Account

### ISSUE THREAD

**Issue by dbarnes18** [CoolCoderSJ/replit-cli#8]
I use a Google account to sign into Replit, and I can't login with cli because of this.....

**Comment by RayhanADev** [comment]
Oooooh, interesting!

@CoolCoderSJ there is a really nice way you could go about this I'll let you know if I can figure something out :)).

**Comment by CoolCoderSJ** [comment]
@RayhanADev do let me know if you find a way :D

@dbarnes18 sorry for this and thanks for bringing it to my attention.
I've released an update (install v 1.1.6) that should help you.
To start, find a value called connect.sid by doing the following-
- Visit https://replit.com/~
- Open Dev tools (` CTRL + SHIFT + I `)
- Click the network tab
- Reload 
- Filter for `~`
- Click cookies
Copy connect.sid

Then run ` $ replit login --sid connect_sid_here`

**Comment by RayhanADev** [comment]
@CoolCoderSJ did you completely remove SID login when you added username and password?

**Comment by CoolCoderSJ** [comment]
@RayhanADev ~~no..~~ Yea...

**Comment by dbarnes18** [comment]
Awesome, thanks!

**Comment by dbarnes18** [comment]
Is there a separate repo for the newer versions?
The latest on here is `v1.0.9`

**Comment by CoolCoderSJ** [comment]
@dbarnes18 
I can't seem to find this comment anymore... (Attached) but-
I've just committed my changes, but I don't make official GitHub releases until a milestone (i.e. Replit CLI reached Cross Platform Availability).

**Comment by dbarnes18** [comment]
Yeah, I realised that it was on GitHub but not Releases which is why I deleted the message.
